name: Build and Release Executable

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install PyInstaller
        run: python -m pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile simple.py

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.Token }}
        with:
          tag_name: v1.0.0 # change to the desired tag name
          release_name: Release v1.0.0 # change to the desired release name
          body: |
            Release of simple executable
          draft: false
          prerelease: false

      - name: Upload Executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.Token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/simple.exe # change to the name of the executable
          asset_name: simple.exe # change to the name of the executable
          asset_content_type: application/octet-stream

      - name: Clone destination repository
        uses: actions/checkout@v2
        with:
          repository: MALIP1/destination # change to the destination repository name

      - name: Push release to destination repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag v1.0.0 # change to the desired tag name
          git push --tags
